# Generated by Django 4.2.9 on 2024-03-08 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_alter_class_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='schedule',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
