# Generated by Django 4.2.9 on 2024-03-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_remove_class_schedule_delete_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='schedule',
            field=models.JSONField(null=True),
        ),
    ]
