# Generated by Django 4.2.9 on 2024-03-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_alter_class_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='class',
            name='schedule',
        ),
        migrations.AddField(
            model_name='class',
            name='schedule',
            field=models.ManyToManyField(to='gym.day'),
        ),
    ]
