# Generated by Django 4.2.9 on 2024-03-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0012_alter_class_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='schedule',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.AddField(
            model_name='class',
            name='schedule',
            field=models.TextField(null=True),
        ),
    ]
