# Generated by Django 4.2.9 on 2024-03-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0016_alter_class_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='intensity',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='class',
            name='level',
            field=models.CharField(max_length=20),
        ),
    ]
