# Generated by Django 4.2.9 on 2024-03-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0017_alter_class_intensity_alter_class_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
