# Generated by Django 4.2.9 on 2024-03-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0021_alter_class_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='category',
            field=models.CharField(auto_created=True, max_length=50, null=True),
        ),
    ]
