# Generated by Django 4.2.9 on 2024-03-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0022_alter_class_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
