# Generated by Django 4.2.9 on 2024-03-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0024_alter_class_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
