# Generated by Django 4.2.9 on 2024-03-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0026_alter_class_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='proffession',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='socialAccounts',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='summary',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
