# Generated by Django 4.2.9 on 2024-03-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0027_trainer_email_trainer_location_trainer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='proffession',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='socialAccounts',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='thumbnail',
            field=models.ImageField(upload_to=''),
        ),
    ]
