# Generated by Django 4.2.9 on 2024-03-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0028_alter_trainer_email_alter_trainer_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
