# Generated by Django 4.2.9 on 2024-04-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0032_remove_class_category_remove_class_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='thumbnail',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='thumbnail',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
